### ISSUE TITLE
`window.document.currentScript is null` error in gh-pages

### ISSUE THREAD

**Issue by bigmistqke** [gzuidhof/coi-serviceworker#11]
Trying to use your package to deploy [an experiment with SharedArrayBuffers on gh-pages](https://github.com/bigmistqke/parallel-filters) but getting the following error `window.document.currentScript is null` using mac/chrome.

**Comment by WebReflection** [comment]
The script *MUST* be synchronous on top of the head of your page, you can't bundle it or import it as a module, as `document.currentScript` works **only** with synchronous scripts while executing.

https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript
