### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'src')

### ISSUE THREAD

**Issue by RalkeyOfficial** [gzuidhof/coi-serviceworker#12]
I get an error when loading this script.
I am loading this script from a Chrome extension I made.

like such
```json
"content_scripts": [
    {
      "matches": ["<all>"],
      "js": ["coi-serviceworker", "content.js"],
      "css": ["style.css"],
      "all_frames": true
    }
  ],
```

![image](https://user-images.githubusercontent.com/30209145/236670838-106605dc-3d92-48d4-afc1-6c4d10f068ef.png)

**Comment by WebReflection** [comment]
You might be better off with whatever this extension does:
https://chrome.google.com/webstore/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj

the content script has no source hence this code cannot re-propose itself as Service Worker and I am not sure there's a solution to that.
