### ISSUE TITLE
Does not work on CrazyGames.com and other game portals

### ISSUE THREAD

**Issue by bergice** [gzuidhof/coi-serviceworker#17]
We've tried uploading zipped builds and iframes using this workaround to CrazyGames.com, but it does not seem to work.

![image](https://github.com/gzuidhof/coi-serviceworker/assets/541886/42c769d8-cbac-4427-a582-127af2a08e15)

Is there some restriction with this workaround we're not aware of?

**Comment by gzuidhof** [comment]
If an iframe is used here, I believe it would be because an iframe with an ancestor that is not cross-origin isolated, can not be cross-origin isolated itself.

Source: https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/

**Comment by bergice** [comment]
> If an iframe is used here, I believe it would be because an iframe with an ancestor that is not cross-origin isolated, can not be cross-origin isolated itself.
> 
> Source: https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/

That's what I thought.

That's weird though, since they mention this workaround as a potential solution in the Godot 4.1 release statement: https://godotengine.org/article/godot-4-1-is-here/#platform-support

> **We are also aware of the complexity setting up web games on hosting platforms which don’t let you set the required CORS headers for SharedArrayBuffer support**. This mostly depends on Safari implementing the coep:credentialless header support, while Chromium-based browsers and Firefox already work fine (especially if you publish on itch.io). There is a [possible workaround](https://github.com/godotengine/godot-proposals/issues/6616) that we are investigating.

**Comment by gzuidhof** [comment]
You might want to ask the hosting platform if it would be possible for them to make their website cross origin isolated.. I am afraid it may be low on their priority list :(.

Almost every Godot game (and other engines that rely on SharedArrayBuffer) must have issues with this though, which will hopefully incentivize them.

**Comment by bergice** [comment]
> You might want to ask the hosting platform if it would be possible for them to make their website cross origin isolated.. I am afraid it may be low on their priority list :(.

They can't since ad providers don't support it.

**Comment by popcar2** [comment]
I'm in the same situation, please let me know if you've managed to get Godot 4 working without cross origin isolation.
