### ISSUE TITLE
Use `credentialless` instead of `require-corp` if supported

### ISSUE THREAD

**Issue by josephrocca** [gzuidhof/coi-serviceworker#2]
The COEP `require-corp` value is annoying because, for example, you can't embed cross-domain images unless those have explicitly got appropriate CORs headers, which isn't usually required (only required if you want to actually read the contents of the image with JavaScript).

WICG is working on making this simpler with the `credentialless` value: https://github.com/WICG/credentiallessness/blob/main/explainer.md Along with the COOP `same-origin` value, this enables cross origin isolation, just like before. The COOP `same-origin` value is also inconvenient in some situations, and so they're working on the `same-origin-allow-popups` value: https://github.com/whatwg/html/issues/7713

The COEP `require-corp` value is already supported (unflagged) in Chrome, and so it might be worth detecting support and using that instead, if it's available.

That said... I typed all of the above, assuming there'd be a simple way to test whether a browser supports a particular header value, but unless my google-fu is failing me today, I don't think it's as easy as I thought it would be?

Either way, I guess it's worth having an issue open for this so that this script can eventually be updated to the "lightest touch" version of cross-origin isolation that is supported broadly across browsers.

P.S. Thanks for your work on this script! Very handy.

**Edit:** For `credentialless` to work properly, a new request object needs to be created if `request.mode` is "no-cors", and the `credentials` value must be set to "omit", like so ([explanation here](https://bugs.chromium.org/p/chromium/issues/detail?id=1309901#c7)):
```js
  if(request.mode === "no-cors") {
      request = new Request(request.url, {
        cache: request.cache,
        credentials: "omit",
        headers: request.headers,
        integrity: request.integrity,
        destination: request.destination,
        keepalive: request.keepalive,
        method: request.method,
        mode: request.mode,
        redirect: request.redirect,
        referrer: request.referrer,
        referrerPolicy: request.referrerPolicy,
        signal: request.signal,
      });
    }
```
Working example:
* https://glitch.com/edit/#!/coep-credentialless-with-serviceworker-fixed
* https://coep-credentialless-with-serviceworker-fixed.glitch.me/

**Comment by gzuidhof** [comment]
Cool I didn't know about `credentialless`. I'm happy to accept a PR that provides a configurable way to use this instead, I think it should still default to `require-corp`. The way this could be implemented is by passing a query value `?coep=auto` to tell the service worker what to serve - it could look at the user agent perhaps (hardly perfect!).
