### ISSUE TITLE
Detection of "credentialless" vs "require-corp" backwards

### ISSUE THREAD

**Issue by mgc8** [gzuidhof/coi-serviceworker#20]
The current code contains the following lines in `coi-serviceworker.js`:
```
67    coepCredentialless: () => !(window.chrome || window.netscape),
```

and
```
44    coepCredentialless ? "credentialless" : "require-corp"
```

According to this logic, it says "_if the browser it NOT (Chrome or Firefox), then add 'credentialless', otherwise add 'require-corp'_"

However, the state of support is exactly backwards -- those are the only browsers that actually can use 'credentialless', and others (**such as Safari**) break when using it.

Testing with a Godot 4 app in Safari 16.5 reveals this exact behaviour -- with the current file the app is broken and we see this in the headers:
<img width="312" alt="Screenshot 2023-08-01 at 01 51 36" src="https://github.com/gzuidhof/coi-serviceworker/assets/7091920/88969b36-d849-4f3c-bdac-73c591f81d20">

The simple change of removing the "!" from line 67 results in the app loading (after clearing caches) and this in the headers:
<img width="299" alt="Screenshot 2023-08-01 at 01 52 03" src="https://github.com/gzuidhof/coi-serviceworker/assets/7091920/b166670f-b062-41f0-acf2-3c4a197ea5e2">

Testing the same in Chrome results in it also switching to "_require-corp_" but working nonetheless, since it supports both versions, however it appears the actual check at line 67 is not working as intended (the result when "true" is not a boolean but the actual "window.chrome" object!). Maybe this would work better?
```
coepCredentialless: () => (window.chrome !== undefined || window.netscape !== undefined),
```

Perhaps a more thorough review of the logic here should be conducted since the variable is used in other parts of the code as well.

**Comment by gzuidhof** [comment]
Ah.. thank you for sharing your findings - this looks like a bug introduced in #13

I have not tested this in various browsers, so I didn't run into this myself. Could you perhaps make a PR with the required changes?

I'm happy to then test them in a few relevant browsers in [BrowserStack](https://www.browserstack.com/).

**Comment by mgc8** [comment]
> As far as I can see, Firefox doesn't support `credentialless`

Firefox **does**  have support for `credentialless`, ever since about version 104, but it's not complete to the same level as Chrome; if anything, the `caniuse.com` website is misleading in this case, as they should either add an asterisk to the evaluation or more accurately portray it as "amber" for "partial support".

Here is the patch from about a year ago:
https://bugzilla.mozilla.org/show_bug.cgi?id=1731778

... and the note on support from version 104:
https://github.com/mozilla/standards-positions/issues/539#issuecomment-1224320026

At the moment, this does require enrolling in an [origin trial](https://wiki.mozilla.org/Origin_Trials), which is done easily just as it was for Chrome -- it is what `itch.io` already did, and you can apply it for your own app as well; here it is in action (check the Response headers, note that the page may take a long time to initialise due to other bugs in Firefox):
https://arturitoproductions.itch.io/coco-and-frogy

Check with:
<img width="216" alt="Screenshot 2023-08-10 at 20 15 01" src="https://github.com/gzuidhof/coi-serviceworker/assets/7091920/522c6b8d-615e-4e91-917d-2259bb4e33dc">

I am not sure there is a universal solution to this, given the current state of browsers :-/ It could be that manual configuration remains the best, as you well pointed out. Having `credentialless` as an option is quite important to a lot of people, since `require-corp` is extremely restrictive, and tends to break a lot more pages because it expects changes on remote (often third-party, inaccessible) resources.

That being said, fully agreed on the `window.chrome` / `window.netscape` manner of detecting browsers, that's a pretty fragile implementation, and anything better based on user-agent would be an improvement!

**Comment by gzuidhof** [comment]
Re-opening this issue, as I think there is space to improve the detection of user agents that support or don't support credentialless
