### ISSUE TITLE
Test with BrowserStack

### ISSUE THREAD

**Issue by tamo** [gzuidhof/coi-serviceworker#22]
> I'm happy to then test them in a few relevant browsers in [BrowserStack](https://www.browserstack.com/).
_Originally posted by @gzuidhof in https://github.com/gzuidhof/coi-serviceworker/issues/20#issuecomment-1659883890_

I have tried to test coi with browserstack/cypress but I can't enable crossOriginIsolated [so far](https://automate.browserstack.com/dashboard/v2/builds/966344f80daecceee45311f77cd3b0169f772ce4/cypress-tests/tests/47a2875c937e26d4dd7fba1c36399aebfc0aa1dbY3lwcmVzcy5zcGVjLmpz?auth_token=8b76fc0905db979083c10b5f1ccf8b5f0773145af25418b1d6713d87bdbe6272&build_token=ZVMvMUtsTDBHZFk5TU5nWk9QSnNuYVY0NHp3M3VuYnU4T3EvSjR4TVU5Zz0tLVFMMG1DNTdPZko3aEQ0Wm5vNVhyclE9PQ==--05f95378ff49e38e74566354a0b49081f091ad23).
If you have a good way to test, please share it. If not, you can close this issue.

**Comment by gzuidhof** [comment]
I had success opening `index.html` through a site like githack. For example with this URL:

https://raw.githack.com/gzuidhof/coi-serviceworker/master/index.html

<img width="1160" alt="Screenshot 2023-08-15 at 10 49 55" src="https://github.com/gzuidhof/coi-serviceworker/assets/1039510/c49e2ebe-5f26-47b6-a870-51720ce67a78">

**Comment by gzuidhof** [comment]
That is hardly automated though!
