### ISSUE TITLE
Code spam-reloads the webpage that it was hosted on

### ISSUE THREAD

**Issue by hkh777uk** [gzuidhof/coi-serviceworker#30]
I have a webapp made with Python and Flask and when I try to use coi-serviceworker on one of my webpages, it just spam-reloads the page. It's most likely a problem in the one _very_ long line of code where it calls the function "doReload" and logs "Reloading page to make use of COOP/COEP Service Worker." to the browser console, and since the script gets included again when the webpage reloads, it reloads the webpage again, creating an infinite loop and causing the spam-reload issue.

**Comment by coder0107git** [comment]
You need to set a tag in localstorage, indexdb, or cookie that indicates if it's already applied. You also could check if a service worker was registered. See the [customization section](https://github.com/gzuidhof/coi-serviceworker?tab=readme-ov-file#customization) in the README for more detials or ideas.

**Comment by hkh777uk** [comment]
> You need to set a tag in localstorage, indexdb, or cookie that indicates if it's already applied. You also could check if a service worker was registered. See the [customization section](https://github.com/gzuidhof/coi-serviceworker?tab=readme-ov-file#customization) in the README for more detials or ideas.

Thanks, I'm pretty sure that would work but it's a bit hard to understand and with Flask, you can just send the headers yourself.
