### ISSUE TITLE
some requests to other domains fail

### ISSUE THREAD

**Issue by dat0825** [gzuidhof/coi-serviceworker#6]
My domain website is `https://myweb.com.vn/`, after using coi-serviceworker, some request to domain `https://abc.com.vn/` it returns fail.
![Screenshot from 2022-06-30 11-39-42](https://user-images.githubusercontent.com/41239003/176594127-e0451d48-fc9a-4a8b-a65e-a51c1fa70d71.png)

**Comment by tamo** [comment]
I don't think that's a bug. That's just what [COI](https://web.dev/i18n/en/coop-coep/) is. 

> These headers instruct the browser to **block** loading of resources ... which haven't opted into being loaded by cross-origin documents ... This also means those resources being loaded cross-origin require opt-ins.
