### ISSUE TITLE
ERR_FAILED if linked from some sites (which are somehow limited by an extension) and if cached

### ISSUE THREAD

**Issue by tamo** [gzuidhof/coi-serviceworker#9]
(Maybe related to #5. Maybe a bug in Chrome? I don't even know whether this is a bug or not. Feel free to close this issue.)

HTMLs using coi-serviceworker sometimes fail to load under some conditions. (Chrome returns ERR_FAILED)
![image](https://user-images.githubusercontent.com/383537/183253158-53e22e96-0a46-4722-a8f4-2c87f9663ac9.png)

For example, I have [a page on github.io](https://tamo.github.io/extsub/) and it works well most of the time.
But it fails if I click a link from [github.com](https://github.com/tamo/extsub/actions/runs/2752052975) to it, at least for the second time with some extensions enabled.
![image](https://user-images.githubusercontent.com/383537/183252858-a6741c72-7d1b-402f-a6fc-65d480d654bc.png)

After a quick investigation, I've found it is reproduced if
- [uMatrix](https://github.com/gorhill/uMatrix) is enabled
  - XHR github.io is not allowed on github.com and
![log](https://user-images.githubusercontent.com/383537/183253854-7973a1cf-c053-41d4-bdc8-908f0cf3bf53.png)
- the page (github.io) is already cached

On the ERR_FAILED page,
- normal reloading doesn't help, but
- hard reloading (Ctrl-Shift-R) wipes the error, and
- modifying the URL (e.g. removing or adding a trailing slash) wipes the error, too.

I suspect it is a common issue in serviceworkers because I have seen some similar errors in other sites which don't use coi-serviceworker.
For example, visiting qiita.com from [google](https://www.google.com/search?q=qiita.com) works fine first time, but it fails second time. Fortunately I can disable serviceworkers on qiita.com with [an extension](https://chrome.google.com/webstore/detail/reject-service-worker/falajmifjcihbmlokgomiklbfmgmnopd) but I cannot on my page because it requires SharedArrayBuffers.

**Comment by tamo** [comment]
This has been discussed at https://github.com/uBlockOrigin/uMatrix-issues/issues/156
So you can safely close this issue as wontfix.

Moving from github.com to github.io, chrome uses github.io's already-registered coi-serviceworker's fetch to fetch github.io itself.
But uMatrix thinks the fetch comes from github.com, not from github.io, and blocks it.
So this is not coi-serviceworker's fault.

If you really want a workaroud for it, tell coi-serviceworker which page it shouldn't fetch.

```
diff --git a/coi-serviceworker.js b/coi-serviceworker.js
index 2e76c21..a5eae6a 100644
--- a/coi-serviceworker.js
+++ b/coi-serviceworker.js
@@ -1,5 +1,6 @@
 /*! coi-serviceworker v0.1.6 - Guido Zuidhof, licensed under MIT */
 let coepCredentialless = false;
+let excludedUrls = new Set();
 if (typeof window === 'undefined') {
     self.addEventListener("install", () => self.skipWaiting());
     self.addEventListener("activate", (event) => event.waitUntil(self.clients.claim()));
@@ -18,6 +19,8 @@ if (typeof window === 'undefined') {
                 });
         } else if (ev.data.type === "coepCredentialless") {
             coepCredentialless = ev.data.value;
+        } else if (ev.data.type === "exclude") {
+            excludedUrls.add(ev.data.value);
         }
     });
 
@@ -26,6 +29,9 @@ if (typeof window === 'undefined') {
         if (r.cache === "only-if-cached" && r.mode !== "same-origin") {
             return;
         }
+        if (excludedUrls.has(r.url)) {
+            return;
+        }
 
         const request = (coepCredentialless && r.mode === "no-cors")
             ? new Request(r, {
@@ -75,6 +81,11 @@ if (typeof window === 'undefined') {
                 value: coi.coepCredentialless(),
             });
 
+            n.serviceWorker.controller.postMessage({
+                type: "exclude",
+                value: window.location.href,
+            })
+
             if (coi.shouldDeregister()) {
                 n.serviceWorker.controller.postMessage({ type: "deregister" });
             }
```

**Comment by gzuidhof** [comment]
Thank you, also for resolving it in the end :)
